apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: cz3hr0lwv-python
  janus-idp.io/tekton: cz3hr0lwv-python
  backstage.io/kubernetes-id: cz3hr0lwv-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: cz3hr0lwv-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
